-- AlterEnum: Add APROVADA_ENGENHEIRO to EtapaStatus
ALTER TYPE "EtapaStatus" ADD VALUE IF NOT EXISTS 'APROVADA_ENGENHEIRO';

-- AlterEnum: Add ETAPA_AGUARDANDO_ADMIN to TipoNotificacao
ALTER TYPE "TipoNotificacao" ADD VALUE IF NOT EXISTS 'ETAPA_AGUARDANDO_ADMIN';

-- AlterEnum: Add GESTOR_FUNDO to UsuarioTipo
ALTER TYPE "UsuarioTipo" ADD VALUE IF NOT EXISTS 'GESTOR_FUNDO';
