-- AlterEnum
ALTER TYPE "UsuarioTipo" ADD VALUE IF NOT EXISTS 'GESTOR';
ALTER TYPE "UsuarioTipo" ADD VALUE IF NOT EXISTS 'ENGENHEIRO';
ALTER TYPE "UsuarioTipo" ADD VALUE IF NOT EXISTS 'COMERCIAL';
ALTER TYPE "UsuarioTipo" ADD VALUE IF NOT EXISTS 'CONSTRUTOR';
