name: Build

on:
  pull_request:
  push:
    branches: [main, staging]
  workflow_dispatch:

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9.0.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm --filter @imbobi/api build

      - uses: actions/upload-artifact@v3
        with:
          name: api-dist
          path: ./services/api/dist/

  build-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9.0.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm --filter @imbobi/web build

      - uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: ./apps/web/.next/
